version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - proxynet

  pc:
    build:
      context: .
    container_name: pc
    environment:
      HOST: "pc"
      DEVICE_TYPE: "laboratory"
      DEBUG_LOG_LEVEL: 0
    networks:
      - proxynet

  server:
    build:
      context: .
    container_name: server
    environment:
      HOST: "server"
      DEVICE_TYPE: "wearable"
      DEVICE_NUM: 3
      DEBUG_LOG_LEVEL: 0
    networks:
      - proxynet

  smartphones:
    build:
      context: .
    container_name: smartphones
    environment:
      HOST: "smartphone"
      DEVICE_TYPE: "wearable"
      DEVICE_NUM: 3
      DEBUG_LOG_LEVEL: 0
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network
